export const GET_PRODUCTS = {
  REQUEST: "GET_PRODUCTS_REQUEST",
  SUCCESS: "GET_PRODUCTS_SUCCESS",
  FAILED: "GET_PRODUCTS_FAILED",
};

export const GET_SINGLE_PRODUCT = {
  REQUEST: "SINGLE_PRODUCT_REQUEST",
  SUCCESS: "SINGLE_PRODUCT_SUCCESS",
  FAILED: "SINGLE_PRODUCT_FAILED",
};

export const CART = {
  ADD_CART_ITEM: "ADD_CART_ITEM",
  REMOVE_CART_ITEM: "REMOVE_CART_ITEM",
};
